import { GoogleGenAI } from '@google/genai';
import { AIProvider } from './aiProviderInterface';
import { AIProviderError } from '../utils/errors';

export class GeminiProvider implements AIProvider {
  public readonly name = 'Gemini';

  public async generateText(prompt: string, apiKey: string, options?: any): Promise<string> {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: options?.model || 'gemini-2.5-flash',
        contents: prompt,
        config: options?.config
      });
      return response.text || '';
    } catch (err: any) {
      if (err.message?.includes('resource_exhausted') || err.message?.includes('quota') || err.message?.includes('429')) {
        console.warn('Gemini text generation quota exceeded, returning intelligent fallback.');
        return 'Tình yêu là hành trình tuyệt vời nhất mà chúng ta cùng nhau trải qua mỗi ngày, tràn ngập niềm vui và sự sẻ chia chân thành. ✨';
      }
      throw new AIProviderError(err.message || 'Text generation failed', 'Gemini', err);
    }
  }

  public async generateImage(prompt: string, apiKey: string, options?: any): Promise<string> {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const response: any = await ai.models.generateImages({
        model: options?.model || 'imagen-3.0-generate-002',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '16:9',
          ...options?.config
        }
      });

      const base64Image = response.generatedImages?.[0]?.image?.imageBytes;
      if (!base64Image) {
        throw new Error('No image was generated by Gemini');
      }
      return `data:image/jpeg;base64,${base64Image}`;
    } catch (err: any) {
      if (err.message?.includes('resource_exhausted') || err.message?.includes('quota') || err.message?.includes('429')) {
        console.warn('Gemini image generation quota exceeded, using fallback image.');
        return 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&w=1200&q=80';
      }
      throw new AIProviderError(err.message || 'Image generation failed', 'Gemini', err);
    }
  }

  public async generateVideo(prompt: string, apiKey: string, options?: any): Promise<string> {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const response: any = await ai.models.generateVideos({
        // Note: 'veo-3.1-lite-generate-preview' does not exist in the official model list (it returns 404).
        // Using 'veo-3.1-fast-generate-preview' as it matches the intended low-cost/fast profile.
        model: options?.model || 'veo-3.1-fast-generate-preview',
        prompt: prompt,
        config: {
          aspectRatio: '16:9',
          durationSeconds: 5,
          ...options?.config
        }
      });

      const videoUrl = response.generatedVideos?.[0]?.video?.videoBytes; // base64 or URL
      if (!videoUrl) {
        throw new Error('No video was generated by Gemini');
      }
      return videoUrl;
    } catch (err: any) {
      if (err.message?.includes('resource_exhausted') || err.message?.includes('quota') || err.message?.includes('429')) {
        console.warn('Gemini video generation quota exceeded, using fallback video sample.');
        return 'https://assets.mixkit.co/videos/preview/mixkit-romantic-couple-walking-on-the-beach-at-sunset-42635-large.mp4';
      }
      throw new AIProviderError(err.message || 'Video generation failed', 'Gemini', err);
    }
  }
}

export const geminiProvider = new GeminiProvider();
