import { GoogleGenAI } from '@google/genai';
import { AIProvider } from './aiProviderInterface';
import { AIProviderError } from '../utils/errors';

export class GeminiProvider implements AIProvider {
  public readonly name = 'Gemini';

  public async generateText(prompt: string, apiKey: string, options?: any): Promise<string> {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const response = await ai.models.generateContent({
        model: options?.model || 'gemini-3.5-flash',
        contents: prompt,
        config: options?.config
      });
      return response.text || '';
    } catch (err: any) {
      throw new AIProviderError(err.message || 'Text generation failed', 'Gemini', err);
    }
  }

  public async generateImage(prompt: string, apiKey: string, options?: any): Promise<string> {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const response: any = await ai.models.generateImages({
        model: options?.model || 'gemini-3.1-flash-lite-image',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '16:9',
          ...options?.config
        }
      });

      const base64Image = response.generatedImages?.[0]?.image?.imageBytes;
      if (!base64Image) {
        throw new Error('No image was generated by Gemini');
      }
      return `data:image/jpeg;base64,${base64Image}`;
    } catch (err: any) {
      throw new AIProviderError(err.message || 'Image generation failed', 'Gemini', err);
    }
  }

  public async generateVideo(prompt: string, apiKey: string, options?: any): Promise<string> {
    try {
      const ai = new GoogleGenAI({ apiKey });
      const response: any = await ai.models.generateVideos({
        model: options?.model || 'veo-3.1-lite-generate-preview',
        prompt: prompt,
        config: {
          aspectRatio: '16:9',
          durationSeconds: 5,
          ...options?.config
        }
      });

      const videoUrl = response.generatedVideos?.[0]?.video?.videoBytes; // base64 or URL
      if (!videoUrl) {
        throw new Error('No video was generated by Gemini');
      }
      return videoUrl;
    } catch (err: any) {
      throw new AIProviderError(err.message || 'Video generation failed', 'Gemini', err);
    }
  }
}

export const geminiProvider = new GeminiProvider();
